- name: Update apt packages
  hosts: "{{ target_group | default('all') }}"
  become: true
  vars:
    destination_email: "{{ destination_email }}"
    source_email: "{{ source_email }}"
    source_email_password: "{{ source_email_password }}"

  tasks:

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes
      register: apt_update

    - name: Parse updated packages
      set_fact:
      updated_packages: "{{ apt_update.stdout_lines | select('match', '^Inst.*') | map('regex_replace', '^Inst\\s+(\\S+)\\s+\\[(.+)\\]\\s+\\((.+)\\).*$', '\\1 mis à jour de \\2 vers \\3') | list }}"
      when: apt_update.changed

    - name: Format email body
      set_fact:
      email_body: "Apt update has been run on {{ inventory_hostname }}\n\nUpdated packages:\n{{ apt_update.stdout_lines | default(['No packages updated']) | join('\n') }}"
      when: apt_update.changed

    - name: Send notification email
      mail:
      host: smtp.mail.ovh.net
      port: 465
      secure: always
      username: "{{ source_email }}"
      password: "{{ source_email_password }}"
      from: "Kestra <{{ source_email }}>"
      to: "Kestra <{{ destination_email }}>"
      subject: "Apt update on {{ inventory_hostname }}"
      body: "{{ email_body }}"
      when: apt_update.changed

    - name: Send notification email
      mail:
        host: smtp.mail.ovh.net
        port: 465
        secure: always
        username: "{{ source_email }}"
        password: "{{ source_email_password }}"
        from: "Kestra <{{ source_email }}>"
        to: "Kestra <{{ destination_email }}>"
        subject: "Apt update on {{ inventory_hostname }}"
        body: |
          Apt update has been run on {{ inventory_hostname }}
          Updated packages:
          {{ apt_update.stdout_lines | default(['No packages updated']) | join('\n') }}
      when: apt_update.changed
