- name: Check disk space
  hosts: "{{ target_group | default('all') }}"
  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}' | sed 's/%//'
        executable: /bin/bash
      register: disk_usage
      changed_when: false
      check_mode: false

    - name: Save result to JSON file
      ansible.builtin.copy:
        content: "{{ disk_usage.stdout | to_json }}"
        dest: "/tmp/disk_usage_result.json"

    - name: Return disk usage value
      ansible.builtin.debug:
        msg: "Disk usage is {{ disk_usage.stdout }}%"
