- name: Check disk space
  hosts: "{{ target_group | default('all') }}"
  vars:
    destination_email: "{{ email }}"

  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}' | sed 's/%//'
        executable: /bin/bash
      register: disk_usage
      changed_when: false
      check_mode: false

    - name: Send email alert if disk usage is high
      ansible.builtin.mail:
        to: "{{ destination_email }}"
        subject: "High disk usage alert on {{ inventory_hostname }}"
        body: "Disk usage is at {{ disk_usage.stdout }}% on {{ inventory_hostname }}"
      when: disk_usage.stdout|int > 80