- name: Check disk space
  hosts: "{{ target_group | default('all') }}"
  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}' | sed 's/%//'
        executable: /bin/bash
      register: disk_usage
      changed_when: false
      check_mode: false

    - name: Set disk usage as fact
      ansible.builtin.set_stats:
        data:
          disk_usage: "{{ disk_usage.stdout }}"
        per_host: false
