- name: Check disk space
  hosts: "{{ target_group | default('all') }}"
  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}' | sed 's/%//'
        executable: /bin/bash
      register: disk_usage
      changed_when: false
      check_mode: false

    - name: Return disk usage value
      ansible.builtin.debug:
        msg: "Disk usage is {{ disk_usage.stdout }}%"
