- name: Check disk space
  hosts: "{{ target_group | default('all') }}"
  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}' | sed 's/%//'
        executable: /bin/bash
      register: disk_usage
      changed_when: false
      check_mode: false

    - name: Write disk usage to output file
      ansible.builtin.copy:
        content: "{{ disk_usage.stdout }}"
        dest: "{{ playbook_dir }}/disk_usage.txt"
      delegate_to: localhost
      run_once: true