- name: Update Docker image
  hosts: all
  become: yes
  tasks:
    - name: Check for new images
      shell: |
        docker images --format '{{ '{{' }}.Repository{{ '}}' }}:{{ '{{' }}.Tag{{ '}}' }}' | while read img; do
          latest=$(docker pull $img | grep 'Downloaded newer image' | wc -l)
          if [ "$latest" -gt 0 ]; then echo $img; fi
        done
      register: images_to_update
      changed_when: images_to_update.stdout != ""

    - name: Stop containers
      when: images_to_update.stdout != ""
      block:
        - name: Stopper les conteneurs
          shell: |
            echo '{{ images_to_update.stdout }}' > /tmp/images_list
            docker ps --format '{{ '{{' }}.Image{{ '}}' }} {{ '{{' }}.ID{{ '}}' }}' | grep -f /tmp/images_list | awk '{print $2}' | xargs -r docker stop
            rm /tmp/images_list
          args:
            executable: /bin/bash

    - name: Pull new images
      when: images_to_update.stdout != ""
      shell: "echo '{{ images_to_update.stdout }}' | xargs -I {} docker pull {}"

    - name: Restart containers
      when: images_to_update.stdout != ""
      shell: |
        echo '{{ images_to_update.stdout }}' > /tmp/images_list
        docker ps -a --format '{{ '{{' }}.Image{{ '}}' }} {{ '{{' }}.ID{{ '}}' }}' | grep -f /tmp/images_list | awk '{print $2}' | xargs -r docker start
        rm /tmp/images_list
      args:
        executable: /bin/bash

    - name: Check if containers are running
      when: images_to_update.stdout != ""
      shell: "docker ps --format '{{ '{{' }}.ID{{ '}}' }}' | xargs -r docker inspect --format='{{ '{{' }}.State.Running{{ '}}' }}'"
      register: check_running
      failed_when: "'false' in check_running.stdout"

    - name: Remove old images
      when: images_to_update.stdout != ""
      shell: "docker images --format '{{ '{{' }}.Repository{{ '}}' }}:{{ '{{' }}.Tag{{ '}}' }}' | grep -f /tmp/images_list | xargs -r docker rmi"
      args:
        executable: /bin/bash

    - name: Get Docker Hub changelog
      when: images_to_update.stdout != ""
      shell: |
        for image in $(echo '{{ images_to_update.stdout }}'); do
          repo=$(echo $image | cut -d':' -f1)
          tag=$(echo $image | cut -d':' -f2)
          namespace=$(echo $repo | cut -d'/' -f1)
          image_name=$(echo $repo | cut -d'/' -f2)

          if [ "$namespace" = "$image_name" ]; then
          namespace="library"
          image_name=$repo
          fi

          changelog=$(curl -s "https://registry.hub.docker.com/v2/repositories/${namespace}/${image_name}/tags/${tag}/" | jq -r '.description // "No changelog available"')
          echo "Image: $image"
          echo "Changelog:"
          echo "$changelog"
          echo "-------------------"
        done
        register: changelog_output
      args:
        executable: /bin/bash

    - name: Send email notification
      mail:
        host: smtp.mail.ovh.net
        port: 465
        username: "{{ source_email }}"
        password: "{{ source_email_password }}"
        from: "Kestra <{{ source_email }}>"
        to: "Kestra <{{ destination_email }}>"
        subject: "Docker images updated - Changelog"
        body: |
          The following Docker images have been updated:

          {{ images_to_update.stdout }}

          Changelog details:
          {{ changelog_output.stdout }}

